version: '3'

services:
  cleanarch_database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - clean-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Toor@1234
      POSTGRES_DB: db_cleanarch

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  clean-data: